NASA for beginners/Areas/Admin/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using NASA.Core.Contracts;
using NASA_for_beginners.Areas.Admin.Models;
using NASA_for_beginners.Extensions;

namespace NASA_for_beginners.Areas.Admin.Controllers
{
    public class CourseController : BaseController
    {
        private readonly ICourseService courseService;

        private readonly ITeacher teacherService;

        public CourseController(ICourseService _courseService, ITeacher _teacherService)
        {
            courseService = _courseService;
            teacherService = _teacherService;
        }

        public async Task<IActionResult> Mine()
        {
            var myCourses = new MyCourseViewModel();
            var adminId = User.Id();

            myCourses.BookedCourses = await courseService.AllCoursesByUserId(adminId);
            var teacherId = await teacherService.GetTeacherId(adminId);
            myCourses.AddedCourses = await courseService.AllCoursesByTeacherId(teacherId);


            return View(myCourses);
        }
    }
}

NASA for beginners/Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using NASA.Core.Constants;
using NASA.Core.Contracts.Admin;

namespace NASA_for_beginners.Areas.Admin.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserService userService;

        public UserController(IUserService _userService)
        {
            userService = _userService;
        }
        public async Task<IActionResult> All()
        {
            var model = await userService.All();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Forget(string userId)
        {
            bool result = await userService.Forget(userId);

            if (result)
            {
                TempData[MessageConstant.SuccessMessage] = "User is now forgotten";
            }
            else
            {
                TempData[MessageConstant.ErrorMessage] = "User is unforgetable";
            }
            return RedirectToAction(nameof(All));
        }
    }
}

NASA for beginners/Areas/Admin/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="mt-4 p-5 bg-light text-center">
    <h2 class="display-4">Hello, Admin!</h2>
    <p class="lead mb-1 mt-3">
        This is your administrator area - you can <b>read</b>, <b>create</b>,
        <b>delete</b> and <b>edit</b> courses.
        <br />You can <b>book</b> and <b>leave</b> the free ones, too!
    </p>
    <p class="lead mt-1">
        You can also see <b>all users and teachers</b> and <b>all booked ones</b> in the system.
    </p>
    <hr class="my-4">
    <a asp-area="" asp-controller="Course" asp-action="All"
       class="btn btn-primary btn-lg">All Courses</a>
    <a asp-area="" asp-controller="Course" asp-action="Add"
       class="btn btn-primary btn-lg">Add Course</a>
    <span>  |   </span>
    <a asp-area="Admin" asp-controller="Course" asp-action="Mine"
       class="btn btn-primary btn-lg">My Courses</a>
    <span>  |   </span>
    
    <a asp-area="Admin" asp-controller="User" asp-action="All"
       class="btn btn-primary btn-lg">All Users</a>
</div>